###Register User
POST http://localhost:5000/user-api/register
Content-Type: application/json

{
  "name": "Puish",
  "email": "puish@gmail.com",
  "password": "123456"
}

###Login User
POST http://localhost:5000/user-api/login
Content-Type: application/json

{
  "email": "puish@gmail.com",
  "password": "123456"
}

@token=eyJhbGciOiJIUzI1NiIs...

###Get Profile
GET http://localhost:5000/user-api/profile
Authorization: Bearer {{token}}


###Create Trip
POST http://localhost:5000/trip-api/create-trip
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tripName": "Goa Trip",
  "destination": "Goa",
  "description": "Summer Vacation",
  "startDate": "2026-06-20",
  "endDate": "2026-06-25"
}


###Get All Trips
GET http://localhost:5000/trip-api/all-trips


###Create Itinerary Day
POST http://localhost:5000/itinerary-api/create-day
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tripId": "TRIP_ID",
  "dayNumber": 1,
  "title": "Arrival Day"
}



###Get Itinerary
GET http://localhost:5000/itinerary-api/trip/TRIP_ID
Authorization: Bearer {{token}}


###Create Poll
POST http://localhost:5000/poll-api/create-poll
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tripId": "TRIP_ID",
  "question": "Which hotel should we choose?",
  "options": [
    {
      "text": "Taj Hotel"
    },
    {
      "text": "Novotel"
    }
  ]
}


###Vote in Poll
PUT http://localhost:5000/poll-api/vote/POLL_ID
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "optionIndex": 0
}



###Create Expense
POST http://localhost:5000/expense-api/create-expense
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tripId": "TRIP_ID",
  "title": "Hotel Booking",
  "amount": 12000,
  "participants": ["USER_ID"]
}



###Expense Summary
GET http://localhost:5000/expense-api/summary/TRIP_ID
Authorization: Bearer {{token}}
